CREATE TABLE PASSAGEIRO (
    ID_PASSAGEIRO NUMERIC(6) PRIMARY KEY,
    NOME_PASSAGEIRO VARCHAR(40) NOT NULL,
    TOTAL_PONTOS NUMERIC(6) default 0 NOT NULL,
    EMAIL_PASSAGEIRO VARCHAR(50) NOT NULL UNIQUE
);
CREATE TABLE ESTACAO(
ID_ESTACAO NUMERIC (4) PRIMARY KEY,
PONTOS_ESTACAO NUMERIC (3) NOT NULL,
NOME_ESTACAO VARCHAR(20) NOT NULL
);
CREATE TABLE ALMAS(
ID_ALMAS numeric (4) PRIMARY KEY,
NOME_ALMAS VARCHAR (40) NOT NULL,
HISTORIA_ALMAS VARCHAR(200) NOT NULL,
PONTOS_ALMAS NUMERIC (4) NOT NULL
);
CREATE TABLE ALMASPASSAGEIRO(
ID_CAPTURA NUMERIC (4) PRIMARY KEY,
HORA_CAPTURA TIMESTAMP NOT NULL,
ID_PASSAGEIRO NUMERIC(6) NOT NULL,
ID_ESTACAO NUMERIC (4) NOT NULL,
ID_ALMAS numeric (4) NOT NULL,
FOREIGN KEY (ID_PASSAGEIRO) REFERENCES PASSAGEIRO(ID_PASSAGEIRO),
FOREIGN KEY (ID_ESTACAO) REFERENCES ESTACAO(ID_ESTACAO),
FOREIGN KEY (ID_ALMAS) REFERENCES ALMAS(ID_ALMAS)
);
CREATE sequence seq_passageiros
 MINVALUE 1
MAXVALUE 100000
START WITH 1
INCREMENT BY 1;

INSERT INTO PASSAGEIRO (ID_PASSAGEIRO, NOME_PASSAGEIRO, EMAIL_PASSAGEIRO) VALUES (seq_passageiros.nextval ,'Carlos Eduardo Tsucamoto Chiarelli', 'caduchiarelli@hotmail.com');