CREATE TABLE PASSAGEIRO (
ID_PASSAGEIRO NUMERIC(6) PRIMARY KEY,
NOME_PASSAGEIRO VARCHAR2(40) NOT NULL,
TOTAL_PONTOS NUMERIC(6) default 0 NOT NULL,
EMAIL_PASSAGEIRO VARCHAR2(50) NOT NULL UNIQUE
);
CREATE TABLE ESTACAO(
ID_ESTACAO NUMERIC (3) PRIMARY KEY,
NOME_ESTACAO VARCHAR2(100) NOT NULL
);
CREATE TABLE ALMAS(
ID_ALMAS numeric (4) PRIMARY KEY,
NOME_ALMAS VARCHAR2 (40) NOT NULL,
HISTORIA_ALMAS VARCHAR2(1200) NOT NULL,
PONTOS_ALMAS NUMERIC (4) NOT NULL
);
CREATE TABLE ALMASPASSAGEIRO(
ID_CAPTURA NUMERIC (4) PRIMARY KEY,
HORA_CAPTURA TIMESTAMP NOT NULL,
ID_PASSAGEIRO NUMERIC(6) NOT NULL,
ID_ESTACAO NUMERIC (3) NOT NULL,
ID_ALMAS numeric (4) NOT NULL,
FOI_CONSUMIDA CHAR(1) default 'N' NOT NULL,
FOREIGN KEY (ID_PASSAGEIRO) REFERENCES PASSAGEIRO(ID_PASSAGEIRO),
FOREIGN KEY (ID_ESTACAO) REFERENCES ESTACAO(ID_ESTACAO),
FOREIGN KEY (ID_ALMAS) REFERENCES ALMAS(ID_ALMAS)
);

CREATE sequence seq_passageiros
 MINVALUE 1
MAXVALUE 100000
START WITH 1
INCREMENT BY 1;

CREATE sequence seq_estacao
 MINVALUE 1
MAXVALUE 100
START WITH 1
INCREMENT BY 1;

CREATE sequence seq_almas
 MINVALUE 1
MAXVALUE 100
START WITH 1
INCREMENT BY 1;

CREATE sequence seq_ALMASPASSAGEIRO
 MINVALUE 1
MAXVALUE 10000
START WITH 1
INCREMENT BY 1;

INSERT INTO PASSAGEIRO (ID_PASSAGEIRO, NOME_PASSAGEIRO, EMAIL_PASSAGEIRO) VALUES (seq_passageiros.nextval ,'Carlos Eduardo Tsucamoto Chiarelli', 'caduchiarelli@hotmail.com'
);
INSERT INTO ESTACAO (ID_ESTACAO, NOME_ESTACAO) VALUES (seq_estacao.nextval,'jabaquara'
);

INSERT INTO ALMAS (ID_ALMAS, NOME_ALMAS, HISTORIA_ALMAS, PONTOS_ALMAS) VALUES (seq_almas.nextval, 'Faisquinha', 'Faisquinha era um fragmento de energia inquieta que se recusava a apagar, saltando entre dimensões para aquecer corações gelados. Em sua brevidade luminosa, provou que mesmo o menor brilho é capaz de incendiar a imensidão do vazio.', 500
);
CREATE index idx_ALMASPASSAGEIRO
ON ALMASPASSAGEIRO (ID_PASSAGEIRO, ID_ESTACAO);

INSERT INTO ALMASPASSAGEIRO (ID_CAPTURA,HORA_CAPTURA,ID_PASSAGEIRO,ID_ESTACAO,ID_ALMAS) VALUES (seq_ALMASPASSAGEIRO.nextval,CURRENT_TIMESTAMP,1,1,1);
COMMIT;
SELECT 
PASSAGEIRO.NOME_PASSAGEIRO,
ALMASPASSAGEIRO.HORA_CAPTURA
FROM ALMASPASSAGEIRO
INNER JOIN PASSAGEIRO ON PASSAGEIRO.ID_PASSAGEIRO = ALMASPASSAGEIRO.ID_PASSAGEIRO;

SELECT MAX(HORA_CAPTURA)
FROM ALMASPASSAGEIRO
where ID_PASSAGEIRO = 1 and ID_ESTACAO = 1;


UPDATE ALMASPASSAGEIRO
SET FOI_CONSUMIDA = 'S'
WHERE ID_CAPTURA = 1;

DELETE FROM ALMASPASSAGEIRO
WHERE ID_CAPTURA = 1;

Select 
PASSAGEIRO.NOME_PASSAGEIRO,
PASSAGEIRO.TOTAL_PONTOS,
ALMAS.NOME_ALMAS,
ALMASPASSAGEIRO.HORA_CAPTURA,
ALMASPASSAGEIRO.FOI_CONSUMIDA
FROM ALMASPASSAGEIRO
INNER JOIN PASSAGEIRO ON PASSAGEIRO.ID_PASSAGEIRO = ALMASPASSAGEIRO.ID_PASSAGEIRO
INNER JOIN ALMAS on ALMAS.ID_ALMAS = ALMASPASSAGEIRO.ID_ALMAS
WHERE ALMASPASSAGEIRO.ID_PASSAGEIRO = 1
ORDER BY ALMASPASSAGEIRO.HORA_CAPTURA DESC;