CREATE TABLE PASSAGEIRO (
    ID_PASSAGEIRO NUMERIC(4) PRIMARY KEY,
    NOME_PASSAGEIRO VARCHAR(40) NOT NULL,
    TOTAL_PONTOS NUMERIC(6) NOT NULL,
    EMAIL_PASSAGEIRO VARCHAR(50) NOT NULL UNIQUE
);
CREATE TABLE ESTACAO(
    ID_ESTACAO NUMERIC (4) PRIMARY KEY,
    PONTOS_ESTACAO NUMERIC (3) NOT NULL,
    NOME_ESTACAO VARCHAR(20) NOT NULL
);